create extension if not exists pgcrypto;

create table if not exists public.candidates (
  id uuid primary key default gen_random_uuid(),
  name text,
  company text,
  role text,
  experience text,
  skills text[] default '{}',
  source text,
  phone text,
  email text,
  location text,
  highest_education text,
  current_ctc text,
  expected_ctc text,
  notice_period text,
  lwd_or_doj text,
  notes text,
  recruiter_context_notes text,
  next_action text,
  client_name text,
  jd_title text,
  recruiter_id uuid,
  recruiter_name text,
  linkedin text,
  used_in_assessment boolean not null default false,
  assessment_id uuid,
  assigned_to_user_id uuid,
  assigned_to_name text,
  assigned_by_user_id uuid,
  assigned_by_name text,
  assigned_jd_id uuid,
  assigned_jd_title text,
  assigned_at timestamptz,
  last_contact_outcome text,
  last_contact_notes text,
  last_contact_at timestamptz,
  next_follow_up_at timestamptz,
  hidden_from_captured boolean not null default false,
  raw_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
